/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ZooERC165EnforcedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAnimal"
      | "animalsInZoo"
      | "getAnimal"
      | "hearAnimalSound"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAnimal",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "animalsInZoo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnimal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hearAnimalSound",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAnimal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "animalsInZoo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAnimal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hearAnimalSound",
    data: BytesLike
  ): Result;
}

export interface ZooERC165Enforced extends BaseContract {
  connect(runner?: ContractRunner | null): ZooERC165Enforced;
  waitForDeployment(): Promise<this>;

  interface: ZooERC165EnforcedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAnimal: TypedContractMethod<
    [animalId: BytesLike, animal: AddressLike],
    [void],
    "nonpayable"
  >;

  animalsInZoo: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getAnimal: TypedContractMethod<[animalId: BytesLike], [string], "view">;

  hearAnimalSound: TypedContractMethod<[animalId: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAnimal"
  ): TypedContractMethod<
    [animalId: BytesLike, animal: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "animalsInZoo"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAnimal"
  ): TypedContractMethod<[animalId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hearAnimalSound"
  ): TypedContractMethod<[animalId: BytesLike], [string], "view">;

  filters: {};
}
