/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptoCollateralizedStablecoin from "./crypto-collateralized-stablecoin";
export type { cryptoCollateralizedStablecoin };
import type * as erc1155 from "./erc-1155";
export type { erc1155 };
import type * as interfaceAsParam from "./interface-as-param";
export type { interfaceAsParam };
import type * as payableExample from "./payable-example";
export type { payableExample };
