/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptoCollateralizedStablecoin from "./crypto-collateralized-stablecoin";
export type { cryptoCollateralizedStablecoin };
import type * as payableExample from "./payable-example";
export type { payableExample };
