/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnimal,
  IAnimalInterface,
} from "../../../../contracts/solidity/interface-as-param/IAnimal";

const _abi = [
  {
    inputs: [],
    name: "makeSound",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnimal__factory {
  static readonly abi = _abi;
  static createInterface(): IAnimalInterface {
    return new Interface(_abi) as IAnimalInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAnimal {
    return new Contract(address, _abi, runner) as unknown as IAnimal;
  }
}
