/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  Tiger,
  TigerInterface,
} from "../../../../contracts/solidity/interface-as-param/Tiger";

const _abi = [
  {
    inputs: [],
    name: "makeSound",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101738061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ab117c3e14610030575b600080fd5b61003861004e565b604051610045919061011b565b60405180910390f35b60606040518060400160405280600581526020017f526f617221000000000000000000000000000000000000000000000000000000815250905090565b600081519050919050565b600082825260208201905092915050565b60005b838110156100c55780820151818401526020810190506100aa565b60008484015250505050565b6000601f19601f8301169050919050565b60006100ed8261008b565b6100f78185610096565b93506101078185602086016100a7565b610110816100d1565b840191505092915050565b6000602082019050818103600083015261013581846100e2565b90509291505056fea2646970667358221220ae3645a82a1bf448c62097b2a7b9c5a8d56b70e7b295475fb73c8ccf8456674764736f6c634300081c0033";

type TigerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TigerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Tiger__factory extends ContractFactory {
  constructor(...args: TigerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Tiger & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Tiger__factory {
    return super.connect(runner) as Tiger__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TigerInterface {
    return new Interface(_abi) as TigerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Tiger {
    return new Contract(address, _abi, runner) as unknown as Tiger;
  }
}
