/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ZebraERC165,
  ZebraERC165Interface,
} from "../../../../contracts/solidity/interface-as-param/ZebraERC165";

const _abi = [
  {
    inputs: [],
    name: "makeSound",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506103528061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806301ffc9a71461003b578063ab117c3e1461006b575b600080fd5b61005560048036038101906100509190610207565b610089565b604051610062919061024f565b60405180910390f35b610073610103565b60405161008091906102fa565b60405180910390f35b600061009482610140565b806100fc57507fab117c3e000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916827bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916145b9050919050565b60606040518060400160405280600681526020017f4e65696768210000000000000000000000000000000000000000000000000000815250905090565b60007f01ffc9a7000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916827bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916149050919050565b600080fd5b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6101e4816101af565b81146101ef57600080fd5b50565b600081359050610201816101db565b92915050565b60006020828403121561021d5761021c6101aa565b5b600061022b848285016101f2565b91505092915050565b60008115159050919050565b61024981610234565b82525050565b60006020820190506102646000830184610240565b92915050565b600081519050919050565b600082825260208201905092915050565b60005b838110156102a4578082015181840152602081019050610289565b60008484015250505050565b6000601f19601f8301169050919050565b60006102cc8261026a565b6102d68185610275565b93506102e6818560208601610286565b6102ef816102b0565b840191505092915050565b6000602082019050818103600083015261031481846102c1565b90509291505056fea26469706673582212205ec7e463a98e8e7b3742801a4de7a69b730054f2783f8471d09a29929b03137d64736f6c634300081c0033";

type ZebraERC165ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ZebraERC165ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ZebraERC165__factory extends ContractFactory {
  constructor(...args: ZebraERC165ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ZebraERC165 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ZebraERC165__factory {
    return super.connect(runner) as ZebraERC165__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZebraERC165Interface {
    return new Interface(_abi) as ZebraERC165Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ZebraERC165 {
    return new Contract(address, _abi, runner) as unknown as ZebraERC165;
  }
}
